apiVersion: batch/v1
kind: CronJob
metadata:
  name: weather
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: weather
            image: avramstefan/weather-cron
          restartPolicy: OnFailure
