apiVersion: batch/v1
kind: CronJob
metadata:
  name: guess
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: guess
            image: avramstefan/guess-cron-job
          restartPolicy: OnFailure
