apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-location
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-location
  template:
    metadata:
      labels:
        app: weather-location
    spec:
      containers:
      - name: weather-location
        image: avramstefan/location:1.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 5002
        env:
          - name: OPEN_WEATHER_API_KEY
            valueFrom:
              secretKeyRef:
                name: open-weather-api
                key: api-key
---
apiVersion: v1
kind: Service
metadata:
  name: weather-location
spec:
  selector:
    app: weather-location
  ports:
  - port: 5000
    targetPort: 5002
